# Bucket Training Alignment Check

This notebook checks whether the bucket-prepared dataset used for training keeps `x` and `z` aligned.

It reproduces the local training path closely enough to inspect three stages:
1. the prepared bucket dataset returned by `DatasetLoader.load_dataset(...)`
2. the exact train/valid tensor datasets created by `dataset.get_dataloaders(..., return_tensor_datasets=True)`
3. the exact bucket collate step used during training

The key question is whether stored `z` still matches the actual non-pad structure in `x`.

The notebook intentionally skips CLIP/OpenCLIP cache generation for `y`, because that step does not modify the bucketed `x` or `z` tensors or the bucket-collate logic.

In [1]:
import os
import sys
from pathlib import Path
from pprint import pprint

PROJECT_ROOT = Path.cwd().resolve()
if not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
os.chdir(PROJECT_ROOT)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))

from IPython.display import display

from notebooks.bucket_training_alignment_helper import (
    DEFAULT_DATASET_ROOT,
    DEFAULT_TRAINING_CFG,
    build_exact_training_tensor_datasets,
    load_prepared_bucket_dataset,
    maybe_dataframe,
    summarize_manual_collate,
    summarize_prepared_bucket_dataset,
    summarize_tensor_dataset_alignment,
)

In [2]:
DATASET_ROOT = Path(DEFAULT_DATASET_ROOT)
TRAINING_CFG = Path(DEFAULT_TRAINING_CFG)
DEVICE = "cpu"
SPLIT_RATIO = 0.1
SEED = 1234
BATCH_SIZE = None
MODEL_SCALE_FACTOR = 4
MAX_MISMATCH_ROWS = 25
MAX_COLLATE_BUCKETS = 25

print("PROJECT_ROOT =", PROJECT_ROOT)
print("DATASET_ROOT =", DATASET_ROOT)
print("TRAINING_CFG =", TRAINING_CFG)

if not DATASET_ROOT.exists():
    raise FileNotFoundError(
        f"Dataset root does not exist: {DATASET_ROOT}\n"
        "Point DATASET_ROOT to the dataset that is actually used during training."
    )

PROJECT_ROOT = /workspace/qcircuit-generation
DATASET_ROOT = /workspace/qcircuit-generation/datasets/qc_srv_dataset_3to8qubit
TRAINING_CFG = /workspace/qcircuit-generation/conf/training/paper_srv_bucket.yaml

In [3]:
loader, dataset, loader_cfg = load_prepared_bucket_dataset(
    DATASET_ROOT,
    training_cfg_path=TRAINING_CFG,
    batch_size=BATCH_SIZE,
    device=DEVICE,
)

effective_batch_size = loader_cfg["training"]["batch_size"]

print("LOADER_CFG =", loader_cfg)
print("dataset type =", type(dataset).__name__)
print("dataset.x shape =", tuple(int(dim) for dim in dataset.x.shape))
print("dataset.z shape =", tuple(int(dim) for dim in dataset.z.shape))
print("dataset.collate_fn =", getattr(dataset, "collate_fn", None))
print("dataset.bucket_batch_size =", getattr(dataset, "bucket_batch_size", None))
print("effective_batch_size =", effective_batch_size)

2026-03-24 07:42:46 - quantum_diffusion.data.dataset - INFO - Detected preprocessed dataset. Loading directly...
[INFO]: Loading tensor from `/workspace/qcircuit-generation/datasets/qc_srv_dataset_3to8qubit/dataset/ds_x.pt` onto device: cpu.
[INFO]: Loading tensor from `/workspace/qcircuit-generation/datasets/qc_srv_dataset_3to8qubit/dataset/ds_y.pt` onto device: cpu.
[INFO]: Loading tensor from `/workspace/qcircuit-generation/datasets/qc_srv_dataset_3to8qubit/dataset/ds_z.pt` onto device: cpu.
[INFO]: Instantiated config_dataset from given config on cpu.
2026-03-24 07:42:55 - quantum_diffusion.data.dataset - INFO - Dataset loaded from /workspace/qcircuit-generation/datasets/qc_srv_dataset_3to8qubit

  0%|          | 0/1 [00:00<?, ?it/s]

 - balance_tensor_dataset, njobs=1, number of samples=2463286
 - uniquify_tensor_dataset, number of samples now 2463286
 - balancing

  0%|          | 0/471 [00:00<?, ?it/s]

 - dataset size after balancing 2463286
Split: Train 9141 - Test 481

2026-03-24 07:43:23 - quantum_diffusion.data.dataset - INFO - Datasets combined into a mixed dataset
LOADER_CFG = {'training': {'padding_mode': 'bucket', 'batch_size': 256}}
dataset type = MixedCircuitsConfigDataset
dataset.x shape = (9141, 256, 8, 52)
dataset.z shape = (9141, 256, 2)
dataset.collate_fn = cut_padding_Bucket_collate_fn
dataset.bucket_batch_size = 256
effective_batch_size = 256

In [4]:
prepared_summary = summarize_prepared_bucket_dataset(
    dataset,
    model_scale_factor=MODEL_SCALE_FACTOR,
    max_examples=MAX_MISMATCH_ROWS,
)

print("=== PREPARED DATASET ===")
pprint({k: v for k, v in prepared_summary.items() if k != "mismatch_examples"})

if prepared_summary["mismatch_examples"]:
    print("\nPREPARED DATASET MISMATCH EXAMPLES")
    display(maybe_dataframe(prepared_summary["mismatch_examples"]))
else:
    print("\nNo x/z mismatches found in the prepared bucket dataset.")

=== PREPARED DATASET ===
{'actual_nonpad_time_unique': [1,
                               2,
                               3,
                               4,
                               5,
                               6,
                               7,
                               8,
                               9,
                               10,
                               11,
                               12,
                               13,
                               14,
                               15,
                               16,
                               17,
                               18,
                               19,
                               20,
                               21,
                               22,
                               23,
                               24,
                               25,
                               26,
                               27,
                               28,
                               29,
                               30,
                               31,
                               32,
                               33,
                               34,
                               35,
                               36,
                               37,
                               38,
                               39,
                               40,
                               41,
                               42,
                               43,
                               44,
                               45,
                               46,
                               47,
                               48],
 'actual_qubits_unique': [3, 4, 5, 6, 7, 8],
 'any_mismatch_count': 1363045,
 'bucket_actual_max_qubits_hist': {3: 737,
                                   4: 1108,
                                   5: 1777,
                                   6: 1706,
                                   7: 1781,
                                   8: 2032},
 'bucket_actual_max_time_hist': {16: 737,
                                 20: 1108,
                                 24: 50,
                                 28: 1727,
                                 32: 111,
                                 36: 1436,
                                 40: 1850,
                                 44: 1897,
                                 48: 225},
 'bucket_actual_qubits_unique_count_hist': {1: 737,
                                            2: 1108,
                                            3: 1777,
                                            4: 1706,
                                            5: 1781,
                                            6: 2032},
 'bucket_actual_time_unique_count_hist': {3: 4,
                                          4: 733,
                                          5: 1108,
                                          6: 50,
                                          7: 1727,
                                          8: 111,
                                          9: 1458,
                                          10: 1962,
                                          11: 1874,
                                          12: 114},
 'bucket_batch_size': 256,
 'bucket_count': 9141,
 'bucket_qubit_max_mismatch_count': 0,
 'bucket_time_max_mismatch_count': 4959,
 'bucket_z_max_qubits_hist': {3: 737,
                              4: 1108,
                              5: 1777,
                              6: 1706,
                              7: 1781,
                              8: 2032},
 'bucket_z_max_time_hist': {16: 737,
                            20: 1108,
                            28: 1777,
                            36: 231,
                            40: 1475,
                            44: 11,
                            48: 2607,
                            52: 1195},
 'bucket_z_qubits_unique_count_hist': {1: 9136, 2: 5},
 'bucket_z_time_unique_count_hist': {3: 125,
                                     4: 636,
                                     5: 1084,
                                     6: 5,
                                     7: 1772,
                                     8: 2,
                                     9: 258,
                                     10: 1449,
                                     11: 446,
                                     12: 2379,
                                     13: 985},
 'collate_fn': 'cut_padding_Bucket_collate_fn',
 'dataset_type': 'MixedCircuitsConfigDataset',
 'expected_bucket_time_unique': [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48],
 'flattened_samples': 2340096,
 'label': 'prepared_dataset',
 'pad_constant': 3,
 'qubit_mismatch_count': 956510,
 'time_mismatch_count': 1031319,
 'x_shape': (9141, 256, 8, 52),
 'z_qubits_unique': [3, 4, 5, 6, 7, 8],
 'z_shape': (9141, 256, 2),
 'z_time_unique': [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52]}

PREPARED DATASET MISMATCH EXAMPLES

,flat_index,bucket_index,sample_index,z_qubits,actual_qubits,z_time,actual_nonpad_time,expected_bucket_time
0,4,0,4,4,3,4,4,4
1,6,0,6,4,4,20,5,8
2,7,0,7,4,4,20,6,8
3,9,0,9,4,4,12,5,8
4,10,0,10,4,4,20,6,8
5,17,0,17,4,4,20,11,12
6,26,0,26,4,3,8,8,8
7,28,0,28,4,4,12,8,8
8,30,0,30,4,4,16,8,8
9,31,0,31,4,3,8,8,8
10,32,0,32,4,4,20,12,12
11,34,0,34,4,3,8,5,8
12,36,0,36,4,4,16,8,8
13,41,0,41,4,4,8,4,4
14,42,0,42,4,3,20,15,16
15,43,0,43,4,4,16,6,8
16,44,0,44,4,3,12,10,12
17,45,0,45,4,3,12,4,4
18,46,0,46,4,4,20,14,16
19,63,0,63,4,4,16,12,12
20,65,0,65,4,4,20,13,16
21,66,0,66,4,4,20,5,8
22,69,0,69,4,4,20,12,12
23,74,0,74,4,4,20,16,16
24,77,0,77,4,4,20,14,16

In [5]:
train_ds, valid_ds = build_exact_training_tensor_datasets(
    dataset,
    split_ratio=SPLIT_RATIO,
    seed=SEED,
    batch_size=effective_batch_size,
)

train_summary = summarize_tensor_dataset_alignment(
    train_ds,
    dataset,
    split_name="train_tensor_dataset",
    model_scale_factor=MODEL_SCALE_FACTOR,
    max_examples=MAX_MISMATCH_ROWS,
)
valid_summary = summarize_tensor_dataset_alignment(
    valid_ds,
    dataset,
    split_name="valid_tensor_dataset",
    model_scale_factor=MODEL_SCALE_FACTOR,
    max_examples=MAX_MISMATCH_ROWS,
)

for name, summary in [("TRAIN TENSOR DATASET", train_summary), ("VALID TENSOR DATASET", valid_summary)]:
    print(f"\n=== {name} ===")
    pprint({k: v for k, v in summary.items() if k != "mismatch_examples"})
    if summary["mismatch_examples"]:
        print("\nMismatch examples")
        display(maybe_dataframe(summary["mismatch_examples"]))
    else:
        print("\nNo x/z mismatches found.")

[INFO]: Not balancing dataset!  balance_max=None

=== TRAIN TENSOR DATASET ===
{'actual_nonpad_time_unique': [1,
                               2,
                               3,
                               4,
                               5,
                               6,
                               7,
                               8,
                               9,
                               10,
                               11,
                               12,
                               13,
                               14,
                               15,
                               16,
                               17,
                               18,
                               19,
                               20,
                               21,
                               22,
                               23,
                               24,
                               25,
                               26,
                               27,
                               28,
                               29,
                               30,
                               31,
                               32,
                               33,
                               34,
                               35,
                               36,
                               37,
                               38,
                               39,
                               40,
                               41,
                               42,
                               43,
                               44,
                               45,
                               46,
                               47,
                               48],
 'actual_qubits_unique': [3, 4, 5, 6, 7, 8],
 'any_mismatch_count': 1226479,
 'bucket_actual_max_qubits_hist': {3: 662,
                                   4: 1002,
                                   5: 1586,
                                   6: 1550,
                                   7: 1612,
                                   8: 1815},
 'bucket_actual_max_time_hist': {16: 662,
                                 20: 1002,
                                 24: 43,
                                 28: 1543,
                                 32: 98,
                                 36: 1310,
                                 40: 1673,
                                 44: 1692,
                                 48: 204},
 'bucket_actual_qubits_unique_count_hist': {1: 662,
                                            2: 1002,
                                            3: 1586,
                                            4: 1550,
                                            5: 1612,
                                            6: 1815},
 'bucket_actual_time_unique_count_hist': {3: 4,
                                          4: 658,
                                          5: 1002,
                                          6: 43,
                                          7: 1543,
                                          8: 98,
                                          9: 1331,
                                          10: 1774,
                                          11: 1671,
                                          12: 103},
 'bucket_batch_size': 256,
 'bucket_count': 8227,
 'bucket_qubit_max_mismatch_count': 0,
 'bucket_time_max_mismatch_count': 4469,
 'bucket_z_max_qubits_hist': {3: 662,
                              4: 1002,
                              5: 1586,
                              6: 1550,
                              7: 1612,
                              8: 1815},
 'bucket_z_max_time_hist': {16: 662,
                            20: 1002,
                            28: 1586,
                            36: 211,
                            40: 1339,
                            44: 10,
                            48: 2350,
                            52: 1067},
 'bucket_z_qubits_unique_count_hist': {1: 8224, 2: 3},
 'bucket_z_time_unique_count_hist': {3: 110,
                                     4: 573,
                                     5: 981,
                                     6: 5,
                                     7: 1581,
                                     8: 2,
                                     9: 236,
                                     10: 1315,
                                     11: 399,
                                     12: 2148,
                                     13: 877},
 'expected_bucket_time_unique': [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48],
 'flattened_samples': 2106112,
 'label': 'train_tensor_dataset',
 'num_buckets_in_split': 8227,
 'pad_constant': 3,
 'qubit_mismatch_count': 860642,
 'tensor_count': 3,
 'time_mismatch_count': 928310,
 'x_shape': (8227, 256, 8, 52),
 'z_qubits_unique': [3, 4, 5, 6, 7, 8],
 'z_shape': (8227, 256, 2),
 'z_time_unique': [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52]}

Mismatch examples

,flat_index,bucket_index,sample_index,z_qubits,actual_qubits,z_time,actual_nonpad_time,expected_bucket_time
0,7,0,7,4,4,16,6,8
1,15,0,15,4,4,20,9,12
2,19,0,19,4,4,12,8,8
3,20,0,20,4,3,8,8,8
4,26,0,26,4,4,20,12,12
5,34,0,34,4,3,12,11,12
6,39,0,39,4,4,16,12,12
7,48,0,48,4,4,20,11,12
8,49,0,49,4,4,16,5,8
9,51,0,51,4,4,8,4,4
10,61,0,61,4,4,16,6,8
11,62,0,62,4,4,16,10,12
12,66,0,66,4,4,16,11,12
13,67,0,67,4,4,16,6,8
14,77,0,77,4,4,16,10,12
15,81,0,81,4,4,20,16,16
16,93,0,93,4,3,12,10,12
17,97,0,97,4,3,16,6,8
18,99,0,99,4,3,12,5,8
19,100,0,100,4,3,12,7,8
20,101,0,101,4,4,20,16,16
21,112,0,112,4,4,16,12,12
22,114,0,114,4,4,16,11,12
23,119,0,119,4,3,16,9,12
24,123,0,123,4,4,16,8,8

=== VALID TENSOR DATASET ===
{'actual_nonpad_time_unique': [1,
                               2,
                               3,
                               4,
                               5,
                               6,
                               7,
                               8,
                               9,
                               10,
                               11,
                               12,
                               13,
                               14,
                               15,
                               16,
                               17,
                               18,
                               19,
                               20,
                               21,
                               22,
                               23,
                               24,
                               25,
                               26,
                               27,
                               28,
                               29,
                               30,
                               31,
                               32,
                               33,
                               34,
                               35,
                               36,
                               37,
                               38,
                               39,
                               40,
                               41,
                               42,
                               43,
                               44,
                               45,
                               46,
                               47],
 'actual_qubits_unique': [3, 4, 5, 6, 7, 8],
 'any_mismatch_count': 136566,
 'bucket_actual_max_qubits_hist': {3: 75,
                                   4: 106,
                                   5: 191,
                                   6: 156,
                                   7: 169,
                                   8: 217},
 'bucket_actual_max_time_hist': {16: 75,
                                 20: 106,
                                 24: 7,
                                 28: 184,
                                 32: 13,
                                 36: 126,
                                 40: 177,
                                 44: 205,
                                 48: 21},
 'bucket_actual_qubits_unique_count_hist': {1: 75,
                                            2: 106,
                                            3: 191,
                                            4: 156,
                                            5: 169,
                                            6: 217},
 'bucket_actual_time_unique_count_hist': {4: 75,
                                          5: 106,
                                          6: 7,
                                          7: 184,
                                          8: 13,
                                          9: 127,
                                          10: 188,
                                          11: 203,
                                          12: 11},
 'bucket_batch_size': 256,
 'bucket_count': 914,
 'bucket_qubit_max_mismatch_count': 0,
 'bucket_time_max_mismatch_count': 490,
 'bucket_z_max_qubits_hist': {3: 75, 4: 106, 5: 191, 6: 156, 7: 169, 8: 217},
 'bucket_z_max_time_hist': {16: 75,
                            20: 106,
                            28: 191,
                            36: 20,
                            40: 136,
                            44: 1,
                            48: 257,
                            52: 128},
 'bucket_z_qubits_unique_count_hist': {1: 912, 2: 2},
 'bucket_z_time_unique_count_hist': {3: 15,
                                     4: 63,
                                     5: 103,
                                     7: 191,
                                     9: 22,
                                     10: 134,
                                     11: 47,
                                     12: 231,
                                     13: 108},
 'expected_bucket_time_unique': [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48],
 'flattened_samples': 233984,
 'label': 'valid_tensor_dataset',
 'num_buckets_in_split': 914,
 'pad_constant': 3,
 'qubit_mismatch_count': 95868,
 'tensor_count': 3,
 'time_mismatch_count': 103009,
 'x_shape': (914, 256, 8, 52),
 'z_qubits_unique': [3, 4, 5, 6, 7, 8],
 'z_shape': (914, 256, 2),
 'z_time_unique': [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52]}

Mismatch examples

,flat_index,bucket_index,sample_index,z_qubits,actual_qubits,z_time,actual_nonpad_time,expected_bucket_time
0,0,0,0,8,8,44,28,28
1,1,0,1,8,5,36,19,20
2,2,0,2,8,8,40,36,36
3,3,0,3,8,6,8,6,8
4,4,0,4,8,6,36,11,12
5,5,0,5,8,8,28,11,12
6,6,0,6,8,5,24,14,16
7,7,0,7,8,5,36,17,20
8,8,0,8,8,7,32,22,24
9,9,0,9,8,5,12,9,12
10,10,0,10,8,3,16,14,16
11,11,0,11,8,5,12,11,12
12,12,0,12,8,7,28,17,20
13,13,0,13,8,6,16,5,8
14,14,0,14,8,7,32,27,28
15,15,0,15,8,6,36,12,12
16,16,0,16,8,5,12,10,12
17,18,0,18,8,4,36,11,12
18,19,0,19,8,3,16,5,8
19,20,0,20,8,4,40,15,16
20,21,0,21,8,8,36,24,24
21,22,0,22,8,5,24,22,24
22,23,0,23,8,3,36,7,8
23,24,0,24,8,5,12,11,12
24,25,0,25,8,8,32,14,16

In [6]:
train_collate = summarize_manual_collate(
    train_ds,
    dataset,
    split_name="train_collate",
    model_scale_factor=MODEL_SCALE_FACTOR,
    max_buckets=MAX_COLLATE_BUCKETS,
)
valid_collate = summarize_manual_collate(
    valid_ds,
    dataset,
    split_name="valid_collate",
    model_scale_factor=MODEL_SCALE_FACTOR,
    max_buckets=MAX_COLLATE_BUCKETS,
)

for name, summary in [("TRAIN COLLATE", train_collate), ("VALID COLLATE", valid_collate)]:
    print(f"\n=== {name} ===")
    pprint({k: v for k, v in summary.items() if k not in {"rows", "mismatch_rows"}})
    if summary["mismatch_rows"]:
        print("\nCollate mismatch rows")
        display(maybe_dataframe(summary["mismatch_rows"]))
    else:
        print("\nAll checked buckets cut to the expected shape.")

=== TRAIN COLLATE ===
{'checked_bucket_count': 25,
 'label': 'train_collate',
 'mismatch_bucket_count': 12}

Collate mismatch rows

,bucket_index,cut_shape,cut_qubits,cut_time,z_max_qubits,actual_max_qubits,z_max_time,actual_max_time,qubits_match_z,qubits_match_actual,time_match_z,time_match_actual
0,1,"(256, 8, 48)",8,48,8,8,48,44,True,True,True,False
1,2,"(256, 8, 52)",8,52,8,8,52,40,True,True,True,False
2,7,"(256, 7, 48)",7,48,7,7,48,40,True,True,True,False
3,8,"(256, 6, 40)",6,40,6,6,40,36,True,True,True,False
4,9,"(256, 8, 52)",8,52,8,8,52,40,True,True,True,False
5,11,"(256, 6, 40)",6,40,6,6,40,36,True,True,True,False
6,12,"(256, 7, 48)",7,48,7,7,48,44,True,True,True,False
7,13,"(256, 8, 48)",8,48,8,8,48,40,True,True,True,False
8,16,"(256, 6, 40)",6,40,6,6,40,36,True,True,True,False
9,20,"(256, 7, 48)",7,48,7,7,48,40,True,True,True,False
10,21,"(256, 8, 52)",8,52,8,8,52,44,True,True,True,False
11,23,"(256, 7, 48)",7,48,7,7,48,44,True,True,True,False

=== VALID COLLATE ===
{'checked_bucket_count': 25,
 'label': 'valid_collate',
 'mismatch_bucket_count': 13}

Collate mismatch rows

,bucket_index,cut_shape,cut_qubits,cut_time,z_max_qubits,actual_max_qubits,z_max_time,actual_max_time,qubits_match_z,qubits_match_actual,time_match_z,time_match_actual
0,0,"(256, 8, 48)",8,48,8,8,48,44,True,True,True,False
1,2,"(256, 6, 40)",6,40,6,6,40,36,True,True,True,False
2,3,"(256, 6, 40)",6,40,6,6,40,32,True,True,True,False
3,5,"(256, 8, 48)",8,48,8,8,48,44,True,True,True,False
4,6,"(256, 7, 48)",7,48,7,7,48,44,True,True,True,False
5,7,"(256, 6, 40)",6,40,6,6,40,36,True,True,True,False
6,8,"(256, 8, 52)",8,52,8,8,52,40,True,True,True,False
7,10,"(256, 8, 52)",8,52,8,8,52,40,True,True,True,False
8,11,"(256, 8, 52)",8,52,8,8,52,40,True,True,True,False
9,13,"(256, 7, 48)",7,48,7,7,48,44,True,True,True,False
10,14,"(256, 7, 48)",7,48,7,7,48,44,True,True,True,False
11,15,"(256, 8, 48)",8,48,8,8,48,40,True,True,True,False
12,19,"(256, 7, 48)",7,48,7,7,48,40,True,True,True,False

In [7]:
summary_counts = {
    "prepared_any_mismatch_count": prepared_summary["any_mismatch_count"],
    "train_tensor_any_mismatch_count": train_summary["any_mismatch_count"],
    "valid_tensor_any_mismatch_count": valid_summary["any_mismatch_count"],
    "train_collate_mismatch_bucket_count": train_collate["mismatch_bucket_count"],
    "valid_collate_mismatch_bucket_count": valid_collate["mismatch_bucket_count"],
}

print("SUMMARY COUNTS")
pprint(summary_counts)

if any(value > 0 for value in summary_counts.values()):
    print(
        "\nResult: this notebook found at least one x/z or cut-shape mismatch in the bucket-training path."
    )
else:
    print(
        "\nResult: this notebook did not find x/z or cut-shape mismatches in the inspected bucket-training path."
    )

SUMMARY COUNTS
{'prepared_any_mismatch_count': 1363045,
 'train_collate_mismatch_bucket_count': 12,
 'train_tensor_any_mismatch_count': 1226479,
 'valid_collate_mismatch_bucket_count': 13,
 'valid_tensor_any_mismatch_count': 136566}

Result: this notebook found at least one x/z or cut-shape mismatch in the bucket-training path.